#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=40gb,walltime=04:00:00
#PBS -N bl.source_estimate

#SBATCH --ntasks-per-node=1
#SBATCH --mem=40G
#SBATCH --time=04:00:00

set -e
set -x

singularity exec \
  docker://aunnikri642/app-freesurfer-mne-source-recon \
  python3 main.py
